### ISSUE TITLE
Old operations not deleted 

### ISSUE THREAD

**Issue by clmntrss** [michalkvasnicak/aws-lambda-graphql#121]
Hello, with my work on #114 .I noticed that the subscription table keeps the old operations like this.

![image](https://user-images.githubusercontent.com/28146493/94249346-11269900-ff20-11ea-8b29-c366189d8a98.png)

Is this intentional? Would it be possible to add the deletion of these old operations with an optional flag or with another way ?

Edit : those operations are deleted when the connection is stopped no problem about this.

**Comment by michalkvasnicak** [comment]
@clmntrss Do you have `TTL` enabled on the table?

**Comment by clmntrss** [comment]
> @clmntrss Do you have `TTL` enabled on the table?

Yes the  `TTL` is enabled and delete with it work on my table.

My problem is more about the case :

- I update my subscription, it creates a new operation ("foo:2") in the table, but the previous one (eg: "foo:1") is not deleted . As if the table represents a history of the different operations operated by the client

**Comment by michalkvasnicak** [comment]
By updating a subscription do you mean changing its variables? In that case it's something that is not handled by this library I think so we'd need to fix that. Because currently library relies on an operation that says you unsubscribed from the subscription but the change of variables obviously works differently and I didn't know about that.

Could you please investigate what operations apollo client sends to backend when you change variables on subscription?

**Comment by clmntrss** [comment]
Could it work if when creating a new operation (foo:2) we unsubscribe (foo:n-1)? 

I'm going to look at what happens in the backend when you change the underwriting variable but this solution could work

**Comment by michalkvasnicak** [comment]
Yes if you first unsubscribe then the operation will be deleted, but the problem with changing variables seems to generate completely new subscription but maybe we can react to that somehow but I don't know what operations is apollo client sending in that case. So it'd be easier to have a look on operations and make a solution based on them.

**Comment by clmntrss** [comment]
From what I saw, when I update the variable of the subscription my client send a GQL_STOP with the ID of the operation then created a new subscription with GQL_START and new variables.

So it's looks like this function is not called when this operation is send from the client 

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/54b59fcebc4ae5bd3ded494e3aab47ae6b3dac9e/packages/aws-lambda-graphql/src/Server.ts#L504

Any idea why ?

**Comment by michalkvasnicak** [comment]
@clmntrss I don't know, we have tests for this event https://github.com/michalkvasnicak/aws-lambda-graphql/blob/d8dc91ac9b7679cbc595a8c856f525faa0a3fc73/packages/aws-lambda-graphql/src/__tests__/Server.test.ts#L997

Do you have `onOperationComplete` handler? Because it could be a case when `onOperationComplete` throws.

**Comment by clmntrss** [comment]
@michalkvasnicak  I don't really understand what you mean by `onOperationComplete` handler. Should I have a custom part to handle it on my server side ? 

My screenshot above is a bit cut but I also received a GQL_COMPLETE message from the back.

Even if I'm not resubscribing ( just stop the subscription ) it still in the database.

Might be an issue with `onOperationComplete` not triggered?

**Comment by michalkvasnicak** [comment]
Ok so you are receiving complete event. In that case it probably fails during deletion from dynamo table. Do you have any logs? It's strange because it seems that the operation is detected and you receive a response. As you pointed out in the code where stop event is handled, complete response is being sent first and after that it deletes the subscription from database. It seems that this step fails.

**Comment by clmntrss** [comment]
Logged the `unsubscribeOperations` and got error with provided key element. 

Since I work on the other issue about adding the multiple subscriptions handler my schema is different from the original one (with RANGE key added on SubscriptionOperation table)

So it looks like `get` operation will need HASH + RANGE to work. But the GQL_STOP protocol is designed to only send the operation id.

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/d8dc91ac9b7679cbc595a8c856f525faa0a3fc73/packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts#L240

So I think i'll try to change this one to `query` with the HASH key to get all elements matched and then delete it if there is no probleme with that.

**Comment by michalkvasnicak** [comment]
Isn't it possible to do without `query`? Because we know `connectionId` and `subscriptionId` then these two should be used as HASH and RANGE. Or do you have different schema? Because as I mentioned in #114 we can use `subscriptionId` as RANGE.

Other thing is when you are going to unsubscribe from all subscriptions on client disconnect, in this case you need `query`.

**Comment by clmntrss** [comment]
Unsubcribe on client disconnect is working well bug I think you used scan on it. https://github.com/michalkvasnicak/aws-lambda-graphql/blob/d8dc91ac9b7679cbc595a8c856f525faa0a3fc73/packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts#L283


Our schema is  `event` as RANGE and `subscriptionId` as HASH a miror of subscription table as you recommended https://github.com/michalkvasnicak/aws-lambda-graphql/issues/114#issuecomment-688187357

A `query` operation seems to be the simplest solution.

But if you prefer the use of a `get` I don't know if it is possible to access the `event(s)` running on graphQL to pass them through `onOperationComplete` function.

Here is the code I used to do the query 

```
 const operation = await this.db
      .query({
        TableName: this.subscriptionOperationsTableName,
        KeyConditionExpression: 'subscriptionId = :id',
        ExpressionAttributeValues: {
          ':id': this.generateSubscriptionId(connectionId, operationId),
        },
      })
      .promise();
```

**Comment by michalkvasnicak** [comment]
Ok I see now. I totally forgot about my proposals, sorry for the confusion. Yes it makes sense to use `query`, I thought that `subscriptionId` is RANGE key at first but now I see the point. I think we can close this as it basically belongs to #114.

**Comment by michalkvasnicak** [comment]
Closing this one as it favour of #114
