### ISSUE TITLE
Unit test subscriptions

### ISSUE THREAD

**Issue by chrishoyes** [michalkvasnicak/aws-lambda-graphql#122]
Hi, as I have said before, great project!

I would like to write some simple unit tests on my subscriptions, even if it is just to mock the dynamo pubsub class and expect the subscribe method to be called.

We are currently using the apollo-server-testing for mutations, and queries, but I have not found a nice way yet of testing subscriptions.

Thank you

**Comment by michalkvasnicak** [comment]
@chrishoyes I'm not sure if `apollo-server-testing` supports `subscription`. But if you want to check if subscription is registered you just need a mock for `PubSub`. With these kind of tests you just test if event is published. But if you want to test whether your subscription resolver is working, it's little bit tricky because you need to trick the server that it actually received an event a starts to process it.

# Testing event publishing

You need to create mocked `PubSub` where you can easily read all the `publish` method calls.

# Testing event processing

This one is tricky. I'd start with test for event processor maybe it'll help you how to achieve that https://github.com/michalkvasnicak/aws-lambda-graphql/blob/d82672591fa0f2ed95b6086afa2ca6085ed58983/packages/aws-lambda-graphql/src/__tests__/DynamoDBEventProcessor.test.ts

You need to separate that because event processing in this library is handled by event processors and not by apollo server.
