### ISSUE TITLE
Change ulid library to support React Native

### ISSUE THREAD

**Issue by samin** [michalkvasnicak/aws-lambda-graphql#15]
Is it possible to change the `ulid` dependency to something like `uuid`? `ulid` uses `crypto`, something not built in to React Native and can cause problems when using the Client implementation.

**Comment by michalkvasnicak** [comment]
It should be quite easy to replace it. I didn't know that it can cause problems in react-native, but it seems that they stub crypto only in browser environment according to https://github.com/ulid/javascript/blob/master/package.json#L47

**Comment by michalkvasnicak** [comment]
Released as `0.4.0`.

**Comment by samin** [comment]
@michalkvasnicak awesome

**Comment by samin** [comment]
@michalkvasnicak some places still use `ulid`:
https://github.com/michalkvasnicak/aws-lambda-graphql/search?q=ulid&unscoped_q=ulid

It's causing errors:
![image](https://user-images.githubusercontent.com/263049/59302295-07651d80-8c6a-11e9-8ec3-24d6827705e1.png)

**Comment by michalkvasnicak** [comment]
Yes I'm sorry, I have `ulid` installed at the package root so typecheck didn't complain. 

I should extract client from `aws-lambda-graphql` package because you don't need `DynamoDBEventStore` in client implementation.

I'll do it the first thing on tomorrow's morning and fix this problem. Sorry for inconvenience :(

**Comment by michalkvasnicak** [comment]
Ok I released `0.5.0` and deprecated `0.4.0`.

`ULID` is being used internally by the server only and client uses incremental number generator for operations.

Also I changed the `Client` import in `aws-lambda-ws-link` because you don't need the whole `aws-lambda-graphql` library in your application but only Client relevant code. 

Let me know if I broke something.

**Comment by samin** [comment]
@michalkvasnicak all is working, thanks
