### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by DavidHooper** [michalkvasnicak/aws-lambda-graphql#3]
Awesome work on exploring how to integrate with API Gateway.

Do you have a roadmap or see any problems with the current implementation?

**Comment by michalkvasnicak** [comment]
Thank you :)

I don't have a roadmap yet because I was just experimenting with this, but probably I'll use it in our application for few stuff like notifications for a start.

Only problem I see now is that API is rather heavy and should be simpler. But again it is "designed" to support multiple event sources (AWS Kinesis, AWS DynamoDB Streams). 

There are few things to make a Client more robust to support unsubscribing. Maybe somehow implement compatibility with existing Apollo's subscription transport, but there is a problem that AWS ApiGateway 2.0 does not support their protocol format. So I had to implement own client.

So I think that:

1. API could be simplified, maybe add a package for each event source
2. Client should be more robust and be able to unsubscribe
