### ISSUE TITLE
Documentation has invalid code

### ISSUE THREAD

**Issue by caseyhoward** [michalkvasnicak/aws-lambda-graphql#39]
In the **Usage (Apollo client + aws-lambda-ws-link)** section it uses a constant called "client" before it's declared.

```ts
const link = new WebSocketLink(client);
const client = new ApolloClient({
  cache: new InMemoryCache(),
  link,
});
```

I'm pretty sure the fix is that it should be `wsClient` instead but I'm not sure since I can't get this library working at all.

**Comment by caseyhoward** [comment]
Also, there are two implementations for the client, but no explanation why to use one over the other. Why are there two different ways to do it?

**Comment by michalkvasnicak** [comment]
@caseyhoward thank you for reporting the problem. I'll fix that.

Two clients exist because when I started this library, it wasn't compatible with Apollo's implementation. Then after the https://github.com/michalkvasnicak/aws-lambda-graphql/pull/27 it is now compatible with legacy client and Apollo's subscription-transport-ws
