### ISSUE TITLE
Cant connect to Websocket 

### ISSUE THREAD

**Issue by Knaackee** [michalkvasnicak/aws-lambda-graphql#65]
I can connect to my web socket using `wscat` and get a connection but the `graphql` playground or the ApolloClient can't. 

- The Playground works and the subscription endpoint is correct
- My Lambda function get called (getting entries in cloudwatch)
- In Chrome Devtools i can see the following web socket message 
- No entries in any DynamoDB table

`Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`

Any Idea?

## Update

I did some logging but it still doesnt work

```
  return async (e: any, c: any) => {
    const result = await server.createWebSocketHandler()(e, c);
    console.log(JSON.stringify(result, null, 2));
    return result;
  };
```

In Cloudwatch i can see the following (wich seems correct but it still **doesnt work**)

```
2020-01-10T13:10:40.893Z	a3f5d717-9b50-4ae1-9055-242946100bd6	INFO	
{
    "body": "",
    "statusCode": 200
}

```

## Update

I cloned the chat-example-server example and changed the config so that the playground is activated and the endpoints are correct. This does not work too.
```

...
const server = new Server({
  connectionManager,
  eventProcessor: new DynamoDBEventProcessor(),
  resolvers,
  subscriptionManager,
  typeDefs,
 // changes
  playground: {
    endpoint: 'https://xxxxx.execute-api.eu-central-1.amazonaws.com/dev/',
    subscriptionEndpoint:
      'wss://xxxxx.execute-api.eu-central-1.amazonaws.com/dev',
  },
  introspection: true,
});

export const handleHttp = server.createHttpHandler();
export const handleWebSocket = server.createWebSocketHandler();
export const handleDynamoDBStream = server.createEventHandler();

```

Have a great day

**Comment by Knaackee** [comment]
You can close this. There was an error in my AWS configuration.

**Comment by IslamWahid** [comment]
@Knaackee what was the error in your AWS config, I have the same issue

**Comment by fridaystreet** [comment]
@Knaackee facing the same issue, Some info on the resolution would be helpful 

Cheers

**Comment by Knaackee** [comment]
My IAM user didn't had the needed permissions. But the error was on my side.

**Comment by ganey** [comment]
I run a custom implementation but read a lot into this pacakge. 

The `Sec-WebSocket-Protocol` error is because API gateway doesn't return any protocol response headers, so the client disconnects.

The 4th parameter in the subscription client example on github specifies the protocols, this needs to be an empty array so that the protocol is not used.

    const wsClient = new SubscriptionClient(
      'ws://localhost:8000', // please provide the uri of the api gateway v2 endpoint
      { lazy: true, reconnect: true },
      null,
      [], //THIS BIT
    );

**Comment by fridaystreet** [comment]
@Knaackee 

Thanks for the reply, Interesting that throws the same error. I ended up working it out, the issue I had is that I was using the apollo/wslink library exclusively for the ws client. I wasn't creating my own client using subscriptions-transport-ws as per the doco. After reading the apollo docs it says it uses subscriptions-transport-ws underneath anyway, so I clearly wrongly assumed it wouldn't matter. what's that saying? lol

Seems the issue is that the apollo wslink implementation of subscriptions-transport-ws adds the Sec-WebSocket-Protocol heaer to the ws request, this causes the browsers to throw an error if the same header isn't present in the response. 

Based on this AWS thread https://forums.aws.amazon.com/thread.jspa?messageID=913401, 

It seems there is still no support for sending back headers in a ws response (ie sending back the Sec-WebSocket-Protocol header, so I would imagine for now at least, using the apollo wslink alone and relying on it's subscriptions-transport-ws implementation won't work. 

I really only moved away from manually creating the subscriptions-transport-ws client first as we have moved to apollo client 3 beta and the updated doco is moving towards just using apollo library.

Anyway, hopefully this helps anyone else stumbling on the issue. 

@michalkvasnicak not sure if it's worth adding a note to the readme around that area as to why explicitly need to use subscriptions-transport-ws client passed to wslink?

Cheers

**Comment by fridaystreet** [comment]
One other thing worth noting is that unfortunately this now breaks playground from working against a live api gateway implementation as it sends that header. Not sure if there is a way to tell it not to, will do some digging

**Comment by IslamWahid** [comment]
I got that error while trying to connect through the playground on Chrome, but it worked when I tried it on Safari. I haven't implemented the client yet.

**Comment by michalkvasnicak** [comment]
@fridaystreet 👍 I think that it'd be helpful to add this to the documentation. Could you please add a note about the problem you described in https://github.com/michalkvasnicak/aws-lambda-graphql/issues/65#issuecomment-604293478 to the documentation?

**Comment by fridaystreet** [comment]
@michalkvasnicak yeah sure no worries. @ganey sorry I hadn't seen your comment before replying, thanks for the info, I hadn't worked out yet why using the vanilla client was different.
